### ISSUE TITLE
Switch to sdl12-compat ?

### ISSUE THREAD

**Issue by traversaro** [conda-forge/sdl-feedstock#5]
The SDL 1.2.15 version is extremly old and full of known bugs and security issues (see https://github.com/libsdl-org/SDL-1.2/compare/release-1.2.15...main and https://discourse.libsdl.org/t/interest-in-a-sdl-1-2-bugfix-release/24784/11). Once it is released, a possible option would be to switch to provide sdl via the `sdl12-compat` project that provide a sdl1 compatibility layer based on sdl2 . 

For doing that, we may need to wait for the first release of sdl12-compat (see https://github.com/libsdl-org/sdl12-compat/issues/53).

FYI @wolfv  @Tobias-Fischer 

Related downstream issue: https://github.com/robotology/robotology-superbuild/issues/815#issuecomment-875551002 .

**Comment by traversaro** [comment]
Based on the answer in https://github.com/libsdl-org/sdl12-compat/issues/53#issuecomment-875683292, I think it probably make sense to swich this feedstock to use `sdl12-compat` under the new version 1.2.50. In this way, any project that actuall requires the old and buggy 1.2.15 can pin `sdl=1.2.15`, while the sdl 1.2.50 will be sdl12-compat .

**Comment by traversaro** [comment]
> Based on the answer in [libsdl-org/sdl12-compat#53 (comment)](https://github.com/libsdl-org/sdl12-compat/issues/53#issuecomment-875683292), I think it probably make sense to swich this feedstock to use `sdl12-compat` under the new version 1.2.50. In this way, any project that actuall requires the old and buggy 1.2.15 can pin `sdl=1.2.15`, while the sdl 1.2.50 will be `sdl12-compat` .

This is also convenient as so it is easy to make sure that the users do not install both `sdl` and `sdl12-compat`. We just need to make sure that the library is fully compatible, see https://conda-forge.org/docs/maintainer/knowledge_base.html#moving-from-an-autotools-build-to-a-cmake-build .

**Comment by traversaro** [comment]
> We just need to make sure that the library is fully compatible, see https://conda-forge.org/docs/maintainer/knowledge_base.html#moving-from-an-autotools-build-to-a-cmake-build .

Regarding point 6 I noticed that at the moment `sdl12-compat` is not installing any file such that `pkg-config --cflags sdl` and `pkg-config --libs sdl` work as expected. We can handle that with a patch, but I opened anyhow an issue upstream: https://github.com/libsdl-org/sdl12-compat/issues/162 .

**Comment by Tobias-Fischer** [comment]
Done in #6 - thanks Silvio!
